@Orleans.ChatClient_HostAddress = http://localhost:60329

### Post message Hello world
POST http://localhost:5084/rooms/all/messages
Accept: application/json
Content-Type: application/json

{
  "message": "Hello, World!"
}

### Post empty
POST http://localhost:5084/rooms/all/messages
Accept: application/json
Content-Type: application/json

{
  "message": null
}

### Post as moderator
POST {{Orleans.ChatClient_HostAddress}}/rooms/all/messages
Accept: application/json
Content-Type: application/json

{
  "message": "Moderator here"
}

###
